# Generated by Django 4.2.17 on 2025-03-12 09:08

import configurations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('faq_description', models.TextField()),
                ('faq_type', models.CharField(blank=True, default='global', max_length=55, null=True)),
                ('issued_by', models.CharField(blank=True, default='Super Admin', max_length=25, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=configurations.models.default_translated_languages, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
